title: Reviewer's Dashboard Docs
description: NLP-powered review analysis using Streamlit, LDA, and sentiment analysis

remote_theme: just-the-docs/just-the-docs
color_scheme: light
markdown: kramdown

github_repo_url: https://github.com/aakinolaj/reviewers-dashboard
logo: /assets/reviewers-logo.png

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_order: 1
include:
  - _includes

defaults:
  -
    scope:
      path: ""
    values:
      head: _includes/head_custom.html

aux_links:
  View on GitHub: https://github.com/aakinolaj/reviewers-dashboard
