theme: jekyll-theme-cayman
title: Reviewer's Dashboard Docs
description: NLP-powered review analysis using Streamlit, LDA, and sentiment analysis

logo: /assets/reviewers-logo.png
show_downloads: false

# GitHub repo link
github_repo_url: https://github.com/aakinolaj/reviewers-dashboard

# Auxiliary nav link
aux_links:
  View on GitHub: https://github.com/aakinolaj/reviewers-dashboard
