theme: jekyll-theme-cayman
title: Reviewer's Dashboard Docs
description: NLP-powered review analysis using Streamlit, LDA, and sentiment analysis

logo: /assets/reviewers-logo.png
show_downloads: false

# Custom fields for documentation structure
github_repo_url: https://github.com/aakinolaj/reviewers-dashboard

# Auxiliary navigation links
aux_links:
  View on GitHub: https://github.com/aakinolaj/reviewers-dashboard

# Optional includes (may be inactive in Cayman theme)
include:
  - _includes

defaults:
  -
    scope:
      path: ""
    values:
      head: _includes/head_custom.html
